stages:
  - build
  - deploy

variables:
  WEB_IMAGE: $CI_PROJECT_NAME:latest
  CONTAINER_NAME: applegame-app

build-app:
  stage: build
  image: node:20-alpine
  tags:
    - docker
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # vite는 dist 폴더를 생성
      - Dockerfile
      - nginx/

deploy-app:
  stage: deploy
  # Docker 명령어를 사용하므로 docker 이미지를 사용
  image: docker:latest
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    # 이제 이 명령어들이 호스트의 Docker 데몬에 직접 전달됩니다.
    - echo "Stopping and removing old container..."
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - echo "Building new Docker image..."
    - docker build -t $WEB_IMAGE 
      --build-arg VITE_COUCHDB_URL=$VITE_COUCHDB_URL
      --build-arg VITE_COUCHDB_DATABASE=$VITE_COUCHDB_DATABASE
      --build-arg VITE_COUCHDB_USER=$VITE_COUCHDB_USER
      --build-arg VITE_COUCHDB_PASSWORD=$VITE_COUCHDB_PASSWORD
      .
    - echo "Running new container..."
    - docker run -d --name $CONTAINER_NAME
      --network traefik
      --label "traefik.enable=true"
      --label "traefik.http.routers.applegame.rule=Host(\`apple.ioplug.net\`)"
      --label "traefik.http.routers.applegame.entrypoints=websecure"
      --label "traefik.http.routers.applegame.tls.certresolver=letsencrypt"
      --label "traefik.http.services.applegame.loadbalancer.server.port=80"
      --label "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      --label "traefik.http.routers.applegame-http.rule=Host(\`apple.ioplug.net\`)"
      --label "traefik.http.routers.applegame-http.entrypoints=web"
      --label "traefik.http.routers.applegame-http.middlewares=redirect-to-https"
      -e VITE_COUCHDB_URL="$VITE_COUCHDB_URL"
      -e VITE_COUCHDB_DATABASE="$VITE_COUCHDB_DATABASE"
      -e VITE_COUCHDB_USER="$VITE_COUCHDB_USER"
      -e VITE_COUCHDB_PASSWORD="$VITE_COUCHDB_PASSWORD"
      $WEB_IMAGE
    - docker image prune -f
