image:
  repository: ghcr.io/digitaltoys/applegame
  tag: "e2407c3"

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  host: apple.ioplug.net
  tlsSecretName: applegame-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: false
  size: 5Gi
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  mountPath: /data

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

extraEnv:
  - name: VITE_COUCHDB_URL
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_URL
  - name: VITE_COUCHDB_ADMIN_USER
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_ADMIN_USER
  - name: VITE_COUCHDB_ADMIN_PASS
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_ADMIN_PASS
  - name: VITE_COUCHDB_DATABASE
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_DATABASE
  - name: VITE_COUCHDB_USER
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_USER
  - name: VITE_COUCHDB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: applegame-secret
        key: VITE_COUCHDB_PASSWORD
