image:
  repository: ghcr.io/digitaltoys/applegame
  tag: "d4b3e95"

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  host: apple.ioplug.net
  tlsSecretName: applegame-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: false
  size: 5Gi
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  mountPath: /data

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

extraEnv: []
